config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teams#index'
  resources :teams, only: [:index, :new, :show, :create]
  resources :users, only: [:new, :create]
  resources :jokes, only: [:new, :create]
  resources :teamusers, only: [:new, :create, :edit, :update]
  resources :likes, only: [:new, :create]
  get '/find', to: 'teams#find', as: 'find_team'
  get '/found', to: 'teams#found', as: 'found_team'
  get '/create-teamuser', to: 'teamusers#create_with_user_id', as: 'create_teamuser'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joke.rb
class Joke < ApplicationRecord
  belongs_to :teamuser
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :joke
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :teamusers
  has_many :users, through: :teamusers
  has_many :jokes
  has_many :likes, through: :jokes
end

app/models/teamuser.rb
class Teamuser < ApplicationRecord
  belongs_to :team
  belongs_to :user, optional: true
  has_many :jokes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :teamusers
  has_many :teams, through: :teamusers
  has_many :likes
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo, :photo, :photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:pseudo, :photo, :photo_cache])
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def new
    @joke = Joke.new
    @team = Team.find(params[:team_id])
    @teamusers = @team.teamusers.map do |teamuser|
      teamuser.teamuser_pseudo
    end
  end

  def create
    @team = Team.find(joke_params[:team_id].to_i)
    @teamuser = Teamuser.find_by(teamuser_pseudo: joke_params[:teamuser_id])
    @joke = Joke.create(description: joke_params[:description].capitalize, teamuser_id: @teamuser.id, team_id: @team.id)
    redirect_to team_path(@team)
  end

  private

  def joke_params
    params.require(:joke).permit(:description, :teamuser_id, :team_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @team = Team.find(like_params[:team])
    @joke = Joke.find(like_params[:joke])
    @like = Like.new(joke_id: like_params[:joke], user_id: current_user.id)

    if @like.save
      @likes_count = @like.joke.likes.count
      respond_to do |format|
        format.html {redirect_to team_path(@team)}
        format.js
      end
    else
      respond_to do |format|
        format.html {render "teams/show"}
        format.js
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:joke, :team)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teams_controller.rb
require 'securerandom'

class TeamsController < ApplicationController
  def index
    @teams = current_user.teams
  end

  def new
    @team = Team.new
  end

  def create
    @code = SecureRandom.urlsafe_base64(5)
    @team = Team.create(name: team_params[:name].capitalize, description: team_params[:description].capitalize, code: @code)
    Teamuser.create(user_id: current_user.id, team_id: @team.id, teamuser_pseudo: current_user.pseudo)
    redirect_to team_path(@team)
  end

  def show
    @team = Team.find(params[:id])
    @users = @team.users
    @teamusers = @team.teamusers
    @jokes = @team.jokes.reverse
    @like = Like.new
  end

  def find
    @team = Team.new
  end


  def found
    @team = Team.find_by(code: team_params[:code].strip)
    redirect_to edit_teamuser_path(@team)
  end

  private

  def team_params
    params.require(:team).permit(:name, :description, :code)
  end

end

app/controllers/teamusers_controller.rb
class TeamusersController < ApplicationController
  def new
    @teamuser = Teamuser.new
  end

  def create
    Teamuser.create(teamuser_pseudo: teamuser_params[:teamuser_pseudo], team_id: teamuser_params[:team_id])
    redirect_to team_path(teamuser_params[:team_id])
  end

  def create_with_user_id
    @teamuser = Teamuser.new
    Teamuser.create(teamuser_pseudo: teamuser_params[:teamuser_pseudo], team_id: teamuser_params[:team_id], user_id: current_user.id)
    redirect_to team_path(teamuser_params[:team_id])
  end

  def edit
    @team = Team.find(params[:id])
    @teamusers = @team.teamusers.map do |teamuser|
      teamuser.teamuser_pseudo if teamuser.user_id.nil?
    end
    @teamuser = Teamuser.new
  end

  def update
    @team = Team.find(teamuser_params[:team_id])
    @teamuser = Teamuser.find_by(teamuser_pseudo: teamuser_params[:teamuser_pseudo])
    @teamuser.update(user_id: current_user.id)
    redirect_to team_path(@team)
  end

  private

  def teamuser_params
    params.require(:teamuser).permit(:teamuser_pseudo, :team_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end

  # def create
  #   @team = Team.find(user_params[:team].to_i)
  #   @user = User.find_or_create_by(pseudo: user_params[:pseudo])
  #   Teamuser.create(user_id: @user.id, team_id: @team.id)
  #   redirect_to team_path(@team)
  # end

  # private

  # def user_params
  #   params.require(:user).permit(:pseudo, :team, :photo)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jokes/new.html.erb
<div class="container">
  <%= simple_form_for(@joke) do |f| %>
    <%= f.input :teamuser_id, collection: @teamusers, label: "Qui a dit quoi ? #balancetonpote" %>
    <%= f.input :description, label: "Citation" %>
    <%= f.input :team_id, as: :hidden, input_html: { value: params[:team_id] }%>
    <%= f.submit "Ajoute une citation", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wooden Spoon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
   <!--  <p class="notice"><%= notice %></p> -->
   <!--  <p class="alert"><%= alert %></p> -->
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/likes/_like.html.erb
<i class="fas fa-heart heart-red" id="heart-btn"></i>

app/views/likes/create.js.erb
var heart = document.getElementById("heart-btn-<%= @joke.id %>");
heart.innerHTML = '<%= j render "like" %>';


var likeCount = document.getElementById("like-nb-<%= @joke.id %>");
likeCount.innerHTML = '<%= @likes_count %>';

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "woodenspoon.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
     <!--  <%= link_to "Accueil", teams_path, class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/teamusers/edit.html.erb
<div class="container">
  <h1> <%= Team.find(params[:id]).name  %> </h1>
  <div>
    <%= simple_form_for(@teamuser, url: teamuser_path, method: :patch) do |f| %>
      <%= f.input :teamuser_pseudo, collection: @teamusers, label: "Qui es-tu ?" %>
      <%= f.input :team_id, as: :hidden, input_html: { value: params[:id] }%>
      <%= f.submit "Rejoins l'équipe", class: 'btn btn-success' %>
    <% end %>
  </div>

  <p class="ou"><strong>OU</strong></p>
  <p>Si tu ne trouves pas ton pseudo dans la liste</p>

  <div>
    <%= simple_form_for(@teamuser, url: create_teamuser_path, method: :get) do |f| %>
      <%= f.input :teamuser_pseudo, label:"Quel est ton pseudo ?" %>
      <%= f.input :team_id, as: :hidden, input_html: { value: params[:id] }%>
      <%= f.submit "Rejoins l'équipe", class: 'btn btn-success' %>
    <% end %>
  </div>

</div>

app/views/teamusers/new.html.erb
<div class="container">
  <%= simple_form_for(@teamuser) do |f| %>
    <%= f.input :teamuser_pseudo, label:"Nom du participant" %>
    <%= f.input :team_id, as: :hidden, input_html: {value: params[:team_id]} %>
    <%= f.submit "Ajouter", class: 'btn btn-success' %>
  <% end %>
</div>